<?php
$query = "SELECT OSE.NUMOS as NUMOS,ITE.NUMITEM,'Ordem de Serviço' AS TIPO,OSE.DHCHAMADA AS DATA,
(SELECT UPPER(LTRIM(RTRIM(AD_PATRIMONIO))) FROM TCSPSS WHERE SERIE = OSE.SERIE) AS Patrimonio,
COS.DESCRICAO AS Status_Chamado,
OOS.DESCROCOROS AS Motivo, 
([sankhya].RETORNAINIEXEC(OSE.NUMOS,ITE.NUMITEM)) AS HREXEC,
OSE.DESCRICAO AS Problema, ITE.SOLUCAO,
OSE.AD_DEPARTAMENTO AS Departamento
FROM TCSOSE OSE
INNER JOIN TCSITE ITE ON OSE.NUMOS = ITE.NUMOS
INNER JOIN TCSCON CON ON (OSE.NUMCONTRATO = CON.NUMCONTRATO)
INNER JOIN TSIEMP EMP ON (CON.CODEMP = EMP.CODEMP)
INNER JOIN TGFPAR PAR ON (OSE.CODPARC = PAR.CODPARC)
INNER JOIN TCSCOS COS ON (OSE.CODCOS = COS.CODCOS)
INNER JOIN TCSOOS OOS ON (ITE.CODOCOROS = OOS.CODOCOROS)
INNER JOIN TCSITS ITS ON (ITE.CODSIT = ITS.CODSIT)
WHERE OSE.DHCHAMADA BETWEEN ? AND ?
AND OSE.NUMCONTRATO IN (SELECT NUMCONTRATO FROM AD_CONNUM WHERE CODUSU = ?)
AND ((SELECT AD_PATRIMONIO FROM TCSPSS WHERE SERIE = OSE.SERIE) = ? OR ? IS NULL)
AND (OSE.NUMOS = ? OR ? IS NULL) ORDER BY DATA";

$lista_motivo = "SELECT CODOCOROS, DESCROCOROS FROM TCSOOS WHERE AD_ATIVO = 'S'";

?>