CREATE DATABASE CURSOPHP;
USE CURSOPHP;
CREATE TABLE USUARIOS(
	ID INTEGER NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(64) NOT NULL,
    EMAIL VARCHAR(64) NOT NULL,
    IDADE SMALLINT NOT NULL,
    SEXO VARCHAR(1) NOT NULL,
    ESTADO_CIVIL VARCHAR(16) NOT NULL,
    HUMANAS tinyint NOT NULL,
    EXATAS TINYINT NOT NULL,
    BIOLOGICAS TINYINT NOT NULL,
    SENHA VARCHAR(32) NOT NULL,
    primary key(ID)

);